export default {
  'Please enter the following data': 'من فضلك ادخل البيانات التالية',
  Email: 'البريد الإلكتروني',
  'Forgot Password': 'نسيت كلمة المرور',
  Password: 'كلمة المرور',
  "Don't have an account?": 'ليس لديك حساب؟',
  'Create an account': 'أنشئ حساب',
  'The name on the card': 'الإسم علي البطاقة',
  Phone: 'رقم الهاتف',
  'National ID': 'الرقم القومى',
  'Front national card image': 'صورة البطاقة الأمامية',
  Welcome: 'أهلا بك',
  'How can we help you?': 'كيف يمكننا مساعدتك؟',
  Service: 'خدمة',
  Winch: 'ونش',
  Day: 'اليوم',
  Time: 'الوقت',
  Wallet: 'المحفظة',
  EGP: 'ج.م',
  'Payment Records': 'سجلات الدفع',
  'My Orders': 'سجل طلباتى',
  'Starting Location': 'موقع الإقلاع',
  'Arrival Location': 'موقع الوصول',
  'Finished Service': 'خدمة منتهية',
  Address: 'العناوين',
  'Password Confirmation': 'تأكيد كلمة المرور',
  'Usage policy': 'سياسة الاستخدام',
  'Contact us': 'إتصل بنا',
  'About the app': 'عن التطبيق',
  Language: 'لغة التطبيق',
  'Share the app': 'شارك التطبيق',
  Logout: 'تسجيل الخروج',
  Name: 'الإسم',
  'Personal data': 'البيانات الشخصية',
  'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح',
  'New Password': 'كلمة المرور الجديدة',
  'New Password Confirmation': 'تأكيد كلمة المرور الجديدة',
  'Password has been modified successfully': 'تم تعديل كلمة المرور بنجاح',
  'You can send a complaint or suggestion here':
    'يمكنك إرسال شكوى او اقتراح هنا',
  'Text of the complaint or suggestion': 'نص الشكوى او الاقتراح',
  Send: 'إرسال',
  'For direct contact': 'للتواصل المباشر',
  'About us': 'عن التطبيق',
  Save: 'حفظ',
  Close: 'إغلاق',
  'Message added successfully': 'تمت إضافة الرسالة بنجاح',
  'Add new ddress': 'إضافة عنوان جديد',
  'Address details': 'تفاصيل العنوان',
  'Edited successfully': 'تم التحرير بنجاح',
  'Added successfully': 'اضيف بنجاح',
  'Address Title': 'العنوان',
  'Deleted successfully': 'تم الحذف بنجاح',
  Add: 'إضافة',
  Send: 'إرسال',
  'About service': 'عن الخدمة',
  'Service details': 'تفاصيل الخدمة',
};
