export default {
  'Please enter the following data': 'من فضلك ادخل البيانات التالية',
  Email: 'البريد الإلكتروني',
  'Forgot Password': 'نسيت كلمة المرور',
  Password: 'كلمة المرور',
  "Don't have an account?": 'ليس لديك حساب؟',
  'Create an account': 'أنشئ حساب',
  'The name on the card': 'الإسم علي البطاقة',
  Phone: 'رقم الهاتف',
  'National ID': 'الرقم القومى',
  'Front card image': 'صورة البطاقة الأمامية',
  Welcome: 'أهلا بك',
  'How can we help you?': 'كيف يمكننا مساعدتك؟',
  Service: 'خدمة',
  Winch: 'ونش',
  Day: 'اليوم',
  Time: 'الوقت',
  Wallet: 'المحفظة',
  EGP: 'ج.م',
  'Payment Records': 'سجلات الدفع',
  'My Orders': 'سجل طلباتى',
  'Starting Location': 'موقع الإقلاع',
  'Arrival Location': 'موقع الوصول',
  'Finished Service': 'خدمة منتهية',
  Address: 'العناوين',
  'Password Confirmation': 'تأكيد كلمة المرور',
  'Usage policy': 'سياسة الاستخدام',
  'Contact us': 'إتصل بنا',
  'About the app': 'عن التطبيق',
  Language: 'لغة التطبيق',
  'Share the app': 'شارك التطبيق',
  Logout: 'تسجيل الخروج',
  Name: 'الإسم',
  'Personal data': 'البيانات الشخصية',
  'Profile updated successfully': 'تم تحديث الملف الشخصي بنجاح',
};
