export default {
  'Please enter the following data': 'من فضلك ادخل البيانات التالية',
  Email: 'البريد الإلكتروني',
  'Forgot Password': 'نسيت كلمة المرور',
  "Don't have an account?": 'ليس لديك حساب؟',
  'Create an account': 'أنشئ حساب',
  'The name on the card': 'الإسم علي البطاقة',
  Phone: 'رقم الهاتف',
  'National ID': 'الرقم القومى',
  'Front card image': 'صورة البطاقة الأمامية',
  Welcome: 'أهلا بك',
  'How can we help you?': 'كيف يمكننا مساعدتك؟',
  Service: 'خدمة',
  Winch: 'ونش',
  Day: 'اليوم',
  Time: 'الوقت',
  Wallet: 'المحفظة',
  EGP: 'ج.م',
  'Payment Records': 'سجلات الدفع',
};
